name: writer
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_markdown_plus: ^1.0.5
  share_plus: ^12.0.0
  file_picker: ^10.3.3
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  showcaseview: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icons8-notepad-96.png"

flutter:
  uses-material-design: true

  assets:
    - .env
