name: Build Flutter APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - name: Get dependencies
        run: flutter pub get

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create key.properties file
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/writer-key.jks

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/SwiftWrite.apk

      - name: Delete Previous Release and Tag
        run: |
          gh release delete latest --yes || echo "No previous release to delete."
          git push origin --delete latest || echo "No previous tag to delete."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/SwiftWrite.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
